DROP DATABASE IF EXISTS MOTIVATOR;

CREATE DATABASE MOTIVATOR;

USE MOTIVATOR;

CREATE TABLE Users (
	user_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(256) NOT NULL,
	lastname VARCHAR(256) NOT NULL,
	password INT NOT NULL,
	partner_id INT UNSIGNED,
	FOREIGN KEY (partner_id) REFERENCES Users(user_id)
);


